name: Build and Publish Package

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read  # For actions/checkout
      packages: write  # For publishing to PyPI
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the Python version compatible with your package

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools_scm

      - name: Build package
        run: |
          python -m build --sdist --wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Confirm success
        run: echo "Package published successfully!"
